export const CREATE_AD = 'CREATE_AD';
export const UPDATE_AD = 'UPDATE_AD';
export const DELETE_AD = 'DELETE_AD';
export const FETCH_ALL_ADS = 'FETCH_ALL_ADS';
export const FETCH_ADS = 'FETCH_ADS';
export const FETCH_ADS_BY_SEARCH = 'FETCH_ADS_BY_SEARCH';
export const FETCH_ADS_BY_USER = 'FETCH_ADS_BY_USER';
export const FETCH_AD = 'FETCH_AD';
export const END_LOADING_ADS = 'END_LOADING_ADS';
export const START_LOADING_ADS = 'START_LOADING_ADS';

export const CREATE_GROUP = 'CREATE_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const FETCH_ALL_GROUPS = 'FETCH_ALL_GROUPS';
export const FETCH_GROUPS_BY_SEARCH = 'FETCH_GROUPS_BY_SEARCH';
export const FETCH_GROUPS_BY_USER = 'FETCH_GROUPS_BY_USER';
export const FETCH_GROUP = 'FETCH_GROUP';
export const COMMENT = 'COMMENT';
export const END_LOADING_GROUPS = 'END_LOADING_GROUPS';
export const START_LOADING_GROUPS = 'START_LOADING_GROUPS';

export const CREATE_BOOK = 'CREATE_BOOK';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';
export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const FETCH_BOOKS_BY_SEARCH = 'FETCH_BOOKS_BY_SEARCH';
export const FETCH_BOOK = 'FETCH_BOOK';
export const COMMENTBOOK = 'COMMENTBOOK';
export const END_LOADING_BOOKS = 'END_LOADING_BOOKS';
export const START_LOADING_BOOKS = 'START_LOADING_BOOKS';

export const CREATE_USERS_BOOK = 'CREATE_USERS_BOOK';
export const UPDATE_USERS_BOOK = 'UPDATE_USERS_BOOK';
export const DELETE_USERS_BOOK = 'DELETE_USERS_BOOK';
export const FETCH_ALL_USERS_BOOKS = 'FETCH_ALL_USERS_BOOKS';
export const END_LOADING_USERS_BOOKS = 'END_LOADING_USERS_BOOKS';
export const START_LOADING_USERS_BOOKS = 'START_LOADING_USERS_BOOKS';

export const CREATE_NEWS = 'CREATE_NEWS';
export const UPDATE_NEWS = 'UPDATE_NEWS';
export const DELETE_NEWS = 'DELETE_NEWS';
export const FETCH_ALL_NEWS = 'FETCH_ALL_NEWS';
export const END_LOADING_NEWS = 'END_LOADING_NEWS';
export const START_LOADING_NEWS = 'START_LOADING_NEWS';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const FETCH_ALL_MESSAGES = 'FETCH_ALL_MESSAGES';
export const FETCH_MESSAGE = 'FETCH_MESSAGE';
export const END_LOADING_MESSAGES = 'END_LOADING_MESSAGES';
export const START_LOADING_MESSAGES = 'START_LOADING_MESSAGES';

export const CREATE_REVIEW = 'CREATE_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const FETCH_ALL_REVIEWS = 'FETCH_ALL_REVIEWS';
export const END_LOADING_REVIEWS = 'END_LOADING_REVIEWS';
export const START_LOADING_REVIEWS = 'START_LOADING_REVIEWS';

export const AUTH = 'AUTH';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const LOGOUT = 'LOGOUT';
export const END_LOADING_USERS = 'END_LOADING_USERS';
export const START_LOADING_USERS = 'START_LOADING_USERS';